# 1. Si el navegador está en inglés, redirige a /en/
[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  conditions = {Language = ["en"]}

# 2. Si el navegador está en español (o cualquier otro), redirige a /es/
[[redirects]]
  from = "/"
  to = "/es/"
  status = 302

# 3. Reglas para que las rutas internas de Angular funcionen (SPA)
[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200
